language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
os:
  - osx
  - linux
sudo: required
install:
  - npm i
  - npm i mocha chai ts-node typings  -g
  - typings install dt~mocha --global --save
  - typings install npm~chai --save
script:
  - npm test